<?php

/**
 * BaseObjednavkyPrijata
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $cislo_obj_id
 * @property integer $stav_id
 * @property integer $zakaznik_id
 * @property integer $faktura_id
 * @property CisloObj $CisloObj
 * @property StavObjednavky $StavObjednavky
 * @property Zakaznik $Zakaznik
 * @property Faktura $Faktura
 * 
 * @method integer           getId()             Returns the current record's "id" value
 * @method integer           getCisloObjId()     Returns the current record's "cislo_obj_id" value
 * @method integer           getStavId()         Returns the current record's "stav_id" value
 * @method integer           getZakaznikId()     Returns the current record's "zakaznik_id" value
 * @method integer           getFakturaId()      Returns the current record's "faktura_id" value
 * @method CisloObj          getCisloObj()       Returns the current record's "CisloObj" value
 * @method StavObjednavky    getStavObjednavky() Returns the current record's "StavObjednavky" value
 * @method Zakaznik          getZakaznik()       Returns the current record's "Zakaznik" value
 * @method Faktura           getFaktura()        Returns the current record's "Faktura" value
 * @method ObjednavkyPrijata setId()             Sets the current record's "id" value
 * @method ObjednavkyPrijata setCisloObjId()     Sets the current record's "cislo_obj_id" value
 * @method ObjednavkyPrijata setStavId()         Sets the current record's "stav_id" value
 * @method ObjednavkyPrijata setZakaznikId()     Sets the current record's "zakaznik_id" value
 * @method ObjednavkyPrijata setFakturaId()      Sets the current record's "faktura_id" value
 * @method ObjednavkyPrijata setCisloObj()       Sets the current record's "CisloObj" value
 * @method ObjednavkyPrijata setStavObjednavky() Sets the current record's "StavObjednavky" value
 * @method ObjednavkyPrijata setZakaznik()       Sets the current record's "Zakaznik" value
 * @method ObjednavkyPrijata setFaktura()        Sets the current record's "Faktura" value
 * 
 * @package    Sipkova E Shop
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseObjednavkyPrijata extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('objednavky_prijata');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('cislo_obj_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('stav_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('zakaznik_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('faktura_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CisloObj', array(
             'local' => 'cislo_obj_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('StavObjednavky', array(
             'local' => 'stav_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Zakaznik', array(
             'local' => 'zakaznik_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('Faktura', array(
             'local' => 'faktura_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'id',
             ),
             'canUpdate' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}