<?php

/**
 * BaseAkce
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $kategorie_id
 * @property string $name
 * @property string $title
 * @property clob $perex
 * @property string $perex_img
 * @property boolean $enabled
 * @property integer $zbozi_id
 * @property timestamp $platne_od
 * @property timestamp $platne_do
 * @property integer $pocet_kusy
 * @property integer $gallery_id
 * @property string $keywords
 * @property string $description
 * @property float $cena
 * @property integer $mena_id
 * @property float $sleva
 * @property clob $popis
 * @property Kategorie $Kategorie
 * @property Gallery $Gallery
 * @property Zbozi $Zbozi
 * @property Mena $Mena
 * 
 * @method integer   getId()           Returns the current record's "id" value
 * @method integer   getKategorieId()  Returns the current record's "kategorie_id" value
 * @method string    getName()         Returns the current record's "name" value
 * @method string    getTitle()        Returns the current record's "title" value
 * @method clob      getPerex()        Returns the current record's "perex" value
 * @method string    getPerexImg()     Returns the current record's "perex_img" value
 * @method boolean   getEnabled()      Returns the current record's "enabled" value
 * @method integer   getZboziId()      Returns the current record's "zbozi_id" value
 * @method timestamp getPlatneOd()     Returns the current record's "platne_od" value
 * @method timestamp getPlatneDo()     Returns the current record's "platne_do" value
 * @method integer   getPocetKusy()    Returns the current record's "pocet_kusy" value
 * @method integer   getGalleryId()    Returns the current record's "gallery_id" value
 * @method string    getKeywords()     Returns the current record's "keywords" value
 * @method string    getDescription()  Returns the current record's "description" value
 * @method float     getCena()         Returns the current record's "cena" value
 * @method integer   getMenaId()       Returns the current record's "mena_id" value
 * @method float     getSleva()        Returns the current record's "sleva" value
 * @method clob      getPopis()        Returns the current record's "popis" value
 * @method Kategorie getKategorie()    Returns the current record's "Kategorie" value
 * @method Gallery   getGallery()      Returns the current record's "Gallery" value
 * @method Zbozi     getZbozi()        Returns the current record's "Zbozi" value
 * @method Mena      getMena()         Returns the current record's "Mena" value
 * @method Akce      setId()           Sets the current record's "id" value
 * @method Akce      setKategorieId()  Sets the current record's "kategorie_id" value
 * @method Akce      setName()         Sets the current record's "name" value
 * @method Akce      setTitle()        Sets the current record's "title" value
 * @method Akce      setPerex()        Sets the current record's "perex" value
 * @method Akce      setPerexImg()     Sets the current record's "perex_img" value
 * @method Akce      setEnabled()      Sets the current record's "enabled" value
 * @method Akce      setZboziId()      Sets the current record's "zbozi_id" value
 * @method Akce      setPlatneOd()     Sets the current record's "platne_od" value
 * @method Akce      setPlatneDo()     Sets the current record's "platne_do" value
 * @method Akce      setPocetKusy()    Sets the current record's "pocet_kusy" value
 * @method Akce      setGalleryId()    Sets the current record's "gallery_id" value
 * @method Akce      setKeywords()     Sets the current record's "keywords" value
 * @method Akce      setDescription()  Sets the current record's "description" value
 * @method Akce      setCena()         Sets the current record's "cena" value
 * @method Akce      setMenaId()       Sets the current record's "mena_id" value
 * @method Akce      setSleva()        Sets the current record's "sleva" value
 * @method Akce      setPopis()        Sets the current record's "popis" value
 * @method Akce      setKategorie()    Sets the current record's "Kategorie" value
 * @method Akce      setGallery()      Sets the current record's "Gallery" value
 * @method Akce      setZbozi()        Sets the current record's "Zbozi" value
 * @method Akce      setMena()         Sets the current record's "Mena" value
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAkce extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('akce');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('kategorie_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('perex', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('perex_img', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('enabled', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('zbozi_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('platne_od', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('platne_do', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
        $this->hasColumn('pocet_kusy', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('cena', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('mena_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sleva', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Kategorie', array(
             'local' => 'kategorie_id',
             'foreign' => 'id'));

        $this->hasOne('Gallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id'));

        $this->hasOne('Zbozi', array(
             'local' => 'zbozi_id',
             'foreign' => 'zbozi_id'));

        $this->hasOne('Mena', array(
             'local' => 'mena_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}