<?php

/**
 * BaseZbozi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $zbozi_id
 * @property integer $kategorie_id
 * @property string $name
 * @property string $title
 * @property clob $perex
 * @property string $perex_img
 * @property string $nazev_img
 * @property string $baleni
 * @property boolean $enabled
 * @property integer $gallery_id
 * @property string $keywords
 * @property string $description
 * @property float $cena
 * @property integer $dph_id
 * @property integer $mena_id
 * @property clob $popis
 * @property float $skladem
 * @property float $min_mno
 * @property integer $dodavatel_id
 * @property Kategorie $Kategorie
 * @property Gallery $Gallery
 * @property Mena $Mena
 * @property Doctrine_Collection $Slozeni
 * @property DPH $DPH
 * @property Dodavatel $Dodavatel
 * @property Doctrine_Collection $PolozkyObj
 * @property Doctrine_Collection $Kosik
 * @property Doctrine_Collection $Akce
 * @property Doctrine_Collection $Ceny
 * 
 * @method integer             getZboziId()      Returns the current record's "zbozi_id" value
 * @method integer             getKategorieId()  Returns the current record's "kategorie_id" value
 * @method string              getName()         Returns the current record's "name" value
 * @method string              getTitle()        Returns the current record's "title" value
 * @method clob                getPerex()        Returns the current record's "perex" value
 * @method string              getPerexImg()     Returns the current record's "perex_img" value
 * @method string              getNazevImg()     Returns the current record's "nazev_img" value
 * @method string              getBaleni()       Returns the current record's "baleni" value
 * @method boolean             getEnabled()      Returns the current record's "enabled" value
 * @method integer             getGalleryId()    Returns the current record's "gallery_id" value
 * @method string              getKeywords()     Returns the current record's "keywords" value
 * @method string              getDescription()  Returns the current record's "description" value
 * @method float               getCena()         Returns the current record's "cena" value
 * @method integer             getDphId()        Returns the current record's "dph_id" value
 * @method integer             getMenaId()       Returns the current record's "mena_id" value
 * @method clob                getPopis()        Returns the current record's "popis" value
 * @method float               getSkladem()      Returns the current record's "skladem" value
 * @method float               getMinMno()       Returns the current record's "min_mno" value
 * @method integer             getDodavatelId()  Returns the current record's "dodavatel_id" value
 * @method Kategorie           getKategorie()    Returns the current record's "Kategorie" value
 * @method Gallery             getGallery()      Returns the current record's "Gallery" value
 * @method Mena                getMena()         Returns the current record's "Mena" value
 * @method Doctrine_Collection getSlozeni()      Returns the current record's "Slozeni" collection
 * @method DPH                 getDPH()          Returns the current record's "DPH" value
 * @method Dodavatel           getDodavatel()    Returns the current record's "Dodavatel" value
 * @method Doctrine_Collection getPolozkyObj()   Returns the current record's "PolozkyObj" collection
 * @method Doctrine_Collection getKosik()        Returns the current record's "Kosik" collection
 * @method Doctrine_Collection getAkce()         Returns the current record's "Akce" collection
 * @method Doctrine_Collection getCeny()         Returns the current record's "Ceny" collection
 * @method Zbozi               setZboziId()      Sets the current record's "zbozi_id" value
 * @method Zbozi               setKategorieId()  Sets the current record's "kategorie_id" value
 * @method Zbozi               setName()         Sets the current record's "name" value
 * @method Zbozi               setTitle()        Sets the current record's "title" value
 * @method Zbozi               setPerex()        Sets the current record's "perex" value
 * @method Zbozi               setPerexImg()     Sets the current record's "perex_img" value
 * @method Zbozi               setNazevImg()     Sets the current record's "nazev_img" value
 * @method Zbozi               setBaleni()       Sets the current record's "baleni" value
 * @method Zbozi               setEnabled()      Sets the current record's "enabled" value
 * @method Zbozi               setGalleryId()    Sets the current record's "gallery_id" value
 * @method Zbozi               setKeywords()     Sets the current record's "keywords" value
 * @method Zbozi               setDescription()  Sets the current record's "description" value
 * @method Zbozi               setCena()         Sets the current record's "cena" value
 * @method Zbozi               setDphId()        Sets the current record's "dph_id" value
 * @method Zbozi               setMenaId()       Sets the current record's "mena_id" value
 * @method Zbozi               setPopis()        Sets the current record's "popis" value
 * @method Zbozi               setSkladem()      Sets the current record's "skladem" value
 * @method Zbozi               setMinMno()       Sets the current record's "min_mno" value
 * @method Zbozi               setDodavatelId()  Sets the current record's "dodavatel_id" value
 * @method Zbozi               setKategorie()    Sets the current record's "Kategorie" value
 * @method Zbozi               setGallery()      Sets the current record's "Gallery" value
 * @method Zbozi               setMena()         Sets the current record's "Mena" value
 * @method Zbozi               setSlozeni()      Sets the current record's "Slozeni" collection
 * @method Zbozi               setDPH()          Sets the current record's "DPH" value
 * @method Zbozi               setDodavatel()    Sets the current record's "Dodavatel" value
 * @method Zbozi               setPolozkyObj()   Sets the current record's "PolozkyObj" collection
 * @method Zbozi               setKosik()        Sets the current record's "Kosik" collection
 * @method Zbozi               setAkce()         Sets the current record's "Akce" collection
 * @method Zbozi               setCeny()         Sets the current record's "Ceny" collection
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZbozi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zbozi');
        $this->hasColumn('zbozi_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('kategorie_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('perex', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('perex_img', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('nazev_img', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('baleni', 'string', 40, array(
             'type' => 'string',
             'length' => 40,
             ));
        $this->hasColumn('enabled', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('cena', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('dph_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mena_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('skladem', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('min_mno', 'float', null, array(
             'type' => 'float',
             'default' => 1,
             ));
        $this->hasColumn('dodavatel_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Kategorie', array(
             'local' => 'kategorie_id',
             'foreign' => 'id'));

        $this->hasOne('Gallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id'));

        $this->hasOne('Mena', array(
             'local' => 'mena_id',
             'foreign' => 'id'));

        $this->hasMany('Slozeni', array(
             'refClass' => 'SlozeniZbozi',
             'local' => 'slozeni_id',
             'foreign' => 'zbozi_id'));

        $this->hasOne('DPH', array(
             'local' => 'dph_id',
             'foreign' => 'id'));

        $this->hasOne('Dodavatel', array(
             'local' => 'dodavatel_id',
             'foreign' => 'id'));

        $this->hasMany('PolozkyObj', array(
             'local' => 'zbozi_id',
             'foreign' => 'zbozi_id'));

        $this->hasMany('Kosik', array(
             'local' => 'zbozi_id',
             'foreign' => 'zbozi_id'));

        $this->hasMany('Akce', array(
             'local' => 'zbozi_id',
             'foreign' => 'zbozi_id'));

        $this->hasMany('Ceny', array(
             'local' => 'zbozi_id',
             'foreign' => 'zbozi_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}