<?php

/**
 * BaseSkupina
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $title
 * @property clob $popis
 * @property float $sleva
 * @property Doctrine_Collection $Setting
 * @property Doctrine_Collection $Zakaznik
 * @property Doctrine_Collection $Ceny
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method string              getTitle()    Returns the current record's "title" value
 * @method clob                getPopis()    Returns the current record's "popis" value
 * @method float               getSleva()    Returns the current record's "sleva" value
 * @method Doctrine_Collection getSetting()  Returns the current record's "Setting" collection
 * @method Doctrine_Collection getZakaznik() Returns the current record's "Zakaznik" collection
 * @method Doctrine_Collection getCeny()     Returns the current record's "Ceny" collection
 * @method Skupina             setId()       Sets the current record's "id" value
 * @method Skupina             setName()     Sets the current record's "name" value
 * @method Skupina             setTitle()    Sets the current record's "title" value
 * @method Skupina             setPopis()    Sets the current record's "popis" value
 * @method Skupina             setSleva()    Sets the current record's "sleva" value
 * @method Skupina             setSetting()  Sets the current record's "Setting" collection
 * @method Skupina             setZakaznik() Sets the current record's "Zakaznik" collection
 * @method Skupina             setCeny()     Sets the current record's "Ceny" collection
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSkupina extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('skupina');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('sleva', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Setting', array(
             'local' => 'id',
             'foreign' => 'vychozi_skupina_id'));

        $this->hasMany('Zakaznik', array(
             'local' => 'id',
             'foreign' => 'skupina_id'));

        $this->hasMany('Ceny', array(
             'local' => 'id',
             'foreign' => 'skupina_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}