<?php

/**
 * BaseKategorieKategorie
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $kategorie_local_id
 * @property integer $kategorie_foreign_id
 * 
 * @method integer            getKategorieLocalId()     Returns the current record's "kategorie_local_id" value
 * @method integer            getKategorieForeignId()   Returns the current record's "kategorie_foreign_id" value
 * @method KategorieKategorie setKategorieLocalId()     Sets the current record's "kategorie_local_id" value
 * @method KategorieKategorie setKategorieForeignId()   Sets the current record's "kategorie_foreign_id" value
 * 
 * @package    Sipkova E Shop
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKategorieKategorie extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kategorie_kategorie');
        $this->hasColumn('kategorie_local_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('kategorie_foreign_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}