<?php

/**
 * BaseCisloObj
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property Doctrine_Collection $Objednavky
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getTitle()      Returns the current record's "title" value
 * @method Doctrine_Collection getObjednavky() Returns the current record's "Objednavky" collection
 * @method CisloObj            setId()         Sets the current record's "id" value
 * @method CisloObj            setTitle()      Sets the current record's "title" value
 * @method CisloObj            setObjednavky() Sets the current record's "Objednavky" collection
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCisloObj extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('cislo_obj');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('title', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Objednavky', array(
             'local' => 'id',
             'foreign' => 'cislo_obj_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}