<?php

/**
 * BaseStavObjednavky
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $title
 * @property clob $popis
 * @property Doctrine_Collection $Objednavky
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method string              getTitle()      Returns the current record's "title" value
 * @method clob                getPopis()      Returns the current record's "popis" value
 * @method Doctrine_Collection getObjednavky() Returns the current record's "Objednavky" collection
 * @method StavObjednavky      setId()         Sets the current record's "id" value
 * @method StavObjednavky      setName()       Sets the current record's "name" value
 * @method StavObjednavky      setTitle()      Sets the current record's "title" value
 * @method StavObjednavky      setPopis()      Sets the current record's "popis" value
 * @method StavObjednavky      setObjednavky() Sets the current record's "Objednavky" collection
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStavObjednavky extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stav_objednavky');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Objednavky', array(
             'local' => 'id',
             'foreign' => 'stav_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}