<?php

/**
 * BasePolozkyFak
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $faktura_id
 * @property integer $zbozi_id
 * @property float $mno
 * @property float $cena
 * @property float $sleva
 * @property integer $mena_id
 * @property Faktura $Faktura
 * @property Zbozi $Zbozi
 * @property Mena $Mena
 * 
 * @method integer    getId()         Returns the current record's "id" value
 * @method integer    getFakturaId()  Returns the current record's "faktura_id" value
 * @method integer    getZboziId()    Returns the current record's "zbozi_id" value
 * @method float      getMno()        Returns the current record's "mno" value
 * @method float      getCena()       Returns the current record's "cena" value
 * @method float      getSleva()      Returns the current record's "sleva" value
 * @method integer    getMenaId()     Returns the current record's "mena_id" value
 * @method Faktura    getFaktura()    Returns the current record's "Faktura" value
 * @method Zbozi      getZbozi()      Returns the current record's "Zbozi" value
 * @method Mena       getMena()       Returns the current record's "Mena" value
 * @method PolozkyFak setId()         Sets the current record's "id" value
 * @method PolozkyFak setFakturaId()  Sets the current record's "faktura_id" value
 * @method PolozkyFak setZboziId()    Sets the current record's "zbozi_id" value
 * @method PolozkyFak setMno()        Sets the current record's "mno" value
 * @method PolozkyFak setCena()       Sets the current record's "cena" value
 * @method PolozkyFak setSleva()      Sets the current record's "sleva" value
 * @method PolozkyFak setMenaId()     Sets the current record's "mena_id" value
 * @method PolozkyFak setFaktura()    Sets the current record's "Faktura" value
 * @method PolozkyFak setZbozi()      Sets the current record's "Zbozi" value
 * @method PolozkyFak setMena()       Sets the current record's "Mena" value
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePolozkyFak extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('polozky_fak');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('faktura_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('zbozi_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mno', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('cena', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('sleva', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('mena_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Faktura', array(
             'local' => 'faktura_id',
             'foreign' => 'id'));

        $this->hasOne('Zbozi', array(
             'local' => 'zbozi_id',
             'foreign' => 'zbozi_id'));

        $this->hasOne('Mena', array(
             'local' => 'mena_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'id',
             ),
             'canUpdate' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}