<?php

/**
 * BaseSkupna
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property float $sleva
 * 
 * @method integer getId()    Returns the current record's "id" value
 * @method string  getName()  Returns the current record's "name" value
 * @method float   getSleva() Returns the current record's "sleva" value
 * @method Skupna  setId()    Sets the current record's "id" value
 * @method Skupna  setName()  Sets the current record's "name" value
 * @method Skupna  setSleva() Sets the current record's "sleva" value
 * 
 * @package    Sipkova E Shop
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSkupna extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('skupna');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('sleva', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}