<?php

/**
 * BaseZaokrouhleni
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property enum $metoda
 * @property Doctrine_Collection $Mena
 * @property Doctrine_Collection $MenaKurz
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method enum                getMetoda()   Returns the current record's "metoda" value
 * @method Doctrine_Collection getMena()     Returns the current record's "Mena" collection
 * @method Doctrine_Collection getMenaKurz() Returns the current record's "MenaKurz" collection
 * @method Zaokrouhleni        setId()       Sets the current record's "id" value
 * @method Zaokrouhleni        setName()     Sets the current record's "name" value
 * @method Zaokrouhleni        setMetoda()   Sets the current record's "metoda" value
 * @method Zaokrouhleni        setMena()     Sets the current record's "Mena" collection
 * @method Zaokrouhleni        setMenaKurz() Sets the current record's "MenaKurz" collection
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseZaokrouhleni extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('zaokrouhleni');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('metoda', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => '1',
              1 => '0.01',
              2 => '0.05',
              3 => '0.1',
              4 => '0.5',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Mena', array(
             'local' => 'id',
             'foreign' => 'zaokrouhleni_id'));

        $this->hasMany('MenaKurz', array(
             'local' => 'id',
             'foreign' => 'zaokrouhleni_id'));
    }
}