<?php

/**
 * BaseSlozeniZbozi
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $slozeni_id
 * @property integer $zbozi_id
 * 
 * @method integer      getSlozeniId()  Returns the current record's "slozeni_id" value
 * @method integer      getZboziId()    Returns the current record's "zbozi_id" value
 * @method SlozeniZbozi setSlozeniId()  Sets the current record's "slozeni_id" value
 * @method SlozeniZbozi setZboziId()    Sets the current record's "zbozi_id" value
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlozeniZbozi extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slozeni_zbozi');
        $this->hasColumn('slozeni_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('zbozi_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}