<?php

/**
 * BaseCeny
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $zbozi_id
 * @property integer $skupina_id
 * @property integer $zakaznik_id
 * @property enum $typ
 * @property enum $dle
 * @property float $cena
 * @property integer $mena_id
 * @property enum $typ_slevy
 * @property float $sleva
 * @property Zbozi $Zbozi
 * @property Skupina $Skupina
 * @property Zakaznik $Zakaznik
 * @property Mena $Mena
 * 
 * @method integer  getId()          Returns the current record's "id" value
 * @method integer  getZboziId()     Returns the current record's "zbozi_id" value
 * @method integer  getSkupinaId()   Returns the current record's "skupina_id" value
 * @method integer  getZakaznikId()  Returns the current record's "zakaznik_id" value
 * @method enum     getTyp()         Returns the current record's "typ" value
 * @method enum     getDle()         Returns the current record's "dle" value
 * @method float    getCena()        Returns the current record's "cena" value
 * @method integer  getMenaId()      Returns the current record's "mena_id" value
 * @method enum     getTypSlevy()    Returns the current record's "typ_slevy" value
 * @method float    getSleva()       Returns the current record's "sleva" value
 * @method Zbozi    getZbozi()       Returns the current record's "Zbozi" value
 * @method Skupina  getSkupina()     Returns the current record's "Skupina" value
 * @method Zakaznik getZakaznik()    Returns the current record's "Zakaznik" value
 * @method Mena     getMena()        Returns the current record's "Mena" value
 * @method Ceny     setId()          Sets the current record's "id" value
 * @method Ceny     setZboziId()     Sets the current record's "zbozi_id" value
 * @method Ceny     setSkupinaId()   Sets the current record's "skupina_id" value
 * @method Ceny     setZakaznikId()  Sets the current record's "zakaznik_id" value
 * @method Ceny     setTyp()         Sets the current record's "typ" value
 * @method Ceny     setDle()         Sets the current record's "dle" value
 * @method Ceny     setCena()        Sets the current record's "cena" value
 * @method Ceny     setMenaId()      Sets the current record's "mena_id" value
 * @method Ceny     setTypSlevy()    Sets the current record's "typ_slevy" value
 * @method Ceny     setSleva()       Sets the current record's "sleva" value
 * @method Ceny     setZbozi()       Sets the current record's "Zbozi" value
 * @method Ceny     setSkupina()     Sets the current record's "Skupina" value
 * @method Ceny     setZakaznik()    Sets the current record's "Zakaznik" value
 * @method Ceny     setMena()        Sets the current record's "Mena" value
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCeny extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('ceny');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('zbozi_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('skupina_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('zakaznik_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('typ', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Cena',
              1 => 'Sleva',
             ),
             ));
        $this->hasColumn('dle', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Skupina',
              1 => 'Zakaznik',
             ),
             ));
        $this->hasColumn('cena', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('mena_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('typ_slevy', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'Cena',
              1 => 'Procenta',
             ),
             ));
        $this->hasColumn('sleva', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Zbozi', array(
             'local' => 'zbozi_id',
             'foreign' => 'zbozi_id'));

        $this->hasOne('Skupina', array(
             'local' => 'skupina_id',
             'foreign' => 'id'));

        $this->hasOne('Zakaznik', array(
             'local' => 'zakaznik_id',
             'foreign' => 'id'));

        $this->hasOne('Mena', array(
             'local' => 'mena_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}