<?php

/**
 * BaseStranky
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $kategorie_id
 * @property string $name
 * @property string $title
 * @property integer $gallery_id
 * @property clob $perex
 * @property clob $popis
 * @property boolean $enabled
 * @property boolean $is_homepage
 * @property string $keywords
 * @property string $description
 * @property Kategorie $Kategorie
 * @property Gallery $Gallery
 * 
 * @method integer   getId()           Returns the current record's "id" value
 * @method integer   getKategorieId()  Returns the current record's "kategorie_id" value
 * @method string    getName()         Returns the current record's "name" value
 * @method string    getTitle()        Returns the current record's "title" value
 * @method integer   getGalleryId()    Returns the current record's "gallery_id" value
 * @method clob      getPerex()        Returns the current record's "perex" value
 * @method clob      getPopis()        Returns the current record's "popis" value
 * @method boolean   getEnabled()      Returns the current record's "enabled" value
 * @method boolean   getIsHomepage()   Returns the current record's "is_homepage" value
 * @method string    getKeywords()     Returns the current record's "keywords" value
 * @method string    getDescription()  Returns the current record's "description" value
 * @method Kategorie getKategorie()    Returns the current record's "Kategorie" value
 * @method Gallery   getGallery()      Returns the current record's "Gallery" value
 * @method Stranky   setId()           Sets the current record's "id" value
 * @method Stranky   setKategorieId()  Sets the current record's "kategorie_id" value
 * @method Stranky   setName()         Sets the current record's "name" value
 * @method Stranky   setTitle()        Sets the current record's "title" value
 * @method Stranky   setGalleryId()    Sets the current record's "gallery_id" value
 * @method Stranky   setPerex()        Sets the current record's "perex" value
 * @method Stranky   setPopis()        Sets the current record's "popis" value
 * @method Stranky   setEnabled()      Sets the current record's "enabled" value
 * @method Stranky   setIsHomepage()   Sets the current record's "is_homepage" value
 * @method Stranky   setKeywords()     Sets the current record's "keywords" value
 * @method Stranky   setDescription()  Sets the current record's "description" value
 * @method Stranky   setKategorie()    Sets the current record's "Kategorie" value
 * @method Stranky   setGallery()      Sets the current record's "Gallery" value
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseStranky extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('stranky');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('kategorie_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('gallery_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('perex', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('popis', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('enabled', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('is_homepage', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('keywords', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Kategorie', array(
             'local' => 'kategorie_id',
             'foreign' => 'id'));

        $this->hasOne('Gallery', array(
             'local' => 'gallery_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => true,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}