<?php

/**
 * BasePlatba
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property string $title
 * @property integer $mena_id
 * @property integer $doprava_id
 * @property float $celkem
 * @property float $cena
 * @property enum $system_platby
 * @property Doprava $Doprava
 * @property Mena $Mena
 * @property Doctrine_Collection $Objednavky
 * @property Doctrine_Collection $Platby
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method string              getTitle()         Returns the current record's "title" value
 * @method integer             getMenaId()        Returns the current record's "mena_id" value
 * @method integer             getDopravaId()     Returns the current record's "doprava_id" value
 * @method float               getCelkem()        Returns the current record's "celkem" value
 * @method float               getCena()          Returns the current record's "cena" value
 * @method enum                getSystemPlatby()  Returns the current record's "system_platby" value
 * @method Doprava             getDoprava()       Returns the current record's "Doprava" value
 * @method Mena                getMena()          Returns the current record's "Mena" value
 * @method Doctrine_Collection getObjednavky()    Returns the current record's "Objednavky" collection
 * @method Doctrine_Collection getPlatby()        Returns the current record's "Platby" collection
 * @method Platba              setId()            Sets the current record's "id" value
 * @method Platba              setName()          Sets the current record's "name" value
 * @method Platba              setTitle()         Sets the current record's "title" value
 * @method Platba              setMenaId()        Sets the current record's "mena_id" value
 * @method Platba              setDopravaId()     Sets the current record's "doprava_id" value
 * @method Platba              setCelkem()        Sets the current record's "celkem" value
 * @method Platba              setCena()          Sets the current record's "cena" value
 * @method Platba              setSystemPlatby()  Sets the current record's "system_platby" value
 * @method Platba              setDoprava()       Sets the current record's "Doprava" value
 * @method Platba              setMena()          Sets the current record's "Mena" value
 * @method Platba              setObjednavky()    Sets the current record's "Objednavky" collection
 * @method Platba              setPlatby()        Sets the current record's "Platby" collection
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlatba extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('platba');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('mena_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('doprava_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('celkem', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('cena', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('system_platby', 'enum', null, array(
             'type' => 'enum',
             'values' => 
             array(
              0 => 'OffLine',
              1 => 'OnLine',
             ),
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Doprava', array(
             'local' => 'doprava_id',
             'foreign' => 'doprava_id'));

        $this->hasOne('Mena', array(
             'local' => 'mena_id',
             'foreign' => 'id'));

        $this->hasMany('Objednavky', array(
             'local' => 'id',
             'foreign' => 'platba_id'));

        $this->hasMany('Platby', array(
             'local' => 'id',
             'foreign' => 'platba_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}