<?php

/**
 * BaseDopravaPobocka
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $doprava_id
 * @property integer $pobocka_id
 * 
 * @method integer        getDopravaId()  Returns the current record's "doprava_id" value
 * @method integer        getPobockaId()  Returns the current record's "pobocka_id" value
 * @method DopravaPobocka setDopravaId()  Sets the current record's "doprava_id" value
 * @method DopravaPobocka setPobockaId()  Sets the current record's "pobocka_id" value
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDopravaPobocka extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('doprava_pobocka');
        $this->hasColumn('doprava_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('pobocka_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}