<?php

/**
 * BaseWebPay
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $requestUrl
 * @property string $merchantNumber
 * @property string $publicKey
 * @property string $privateKey
 * @property string $heslo
 * @property integer $lastOrderNum
 * @property integer $mena_id
 * @property integer $zeme_urceni_id
 * @property boolean $enabled
 * @property string $img
 * @property Mena $Mena
 * @property ZemeUrceni $ZemeUrceni
 * 
 * @method integer    getId()             Returns the current record's "id" value
 * @method string     getRequestUrl()     Returns the current record's "requestUrl" value
 * @method string     getMerchantNumber() Returns the current record's "merchantNumber" value
 * @method string     getPublicKey()      Returns the current record's "publicKey" value
 * @method string     getPrivateKey()     Returns the current record's "privateKey" value
 * @method string     getHeslo()          Returns the current record's "heslo" value
 * @method integer    getLastOrderNum()   Returns the current record's "lastOrderNum" value
 * @method integer    getMenaId()         Returns the current record's "mena_id" value
 * @method integer    getZemeUrceniId()   Returns the current record's "zeme_urceni_id" value
 * @method boolean    getEnabled()        Returns the current record's "enabled" value
 * @method string     getImg()            Returns the current record's "img" value
 * @method Mena       getMena()           Returns the current record's "Mena" value
 * @method ZemeUrceni getZemeUrceni()     Returns the current record's "ZemeUrceni" value
 * @method WebPay     setId()             Sets the current record's "id" value
 * @method WebPay     setRequestUrl()     Sets the current record's "requestUrl" value
 * @method WebPay     setMerchantNumber() Sets the current record's "merchantNumber" value
 * @method WebPay     setPublicKey()      Sets the current record's "publicKey" value
 * @method WebPay     setPrivateKey()     Sets the current record's "privateKey" value
 * @method WebPay     setHeslo()          Sets the current record's "heslo" value
 * @method WebPay     setLastOrderNum()   Sets the current record's "lastOrderNum" value
 * @method WebPay     setMenaId()         Sets the current record's "mena_id" value
 * @method WebPay     setZemeUrceniId()   Sets the current record's "zeme_urceni_id" value
 * @method WebPay     setEnabled()        Sets the current record's "enabled" value
 * @method WebPay     setImg()            Sets the current record's "img" value
 * @method WebPay     setMena()           Sets the current record's "Mena" value
 * @method WebPay     setZemeUrceni()     Sets the current record's "ZemeUrceni" value
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWebPay extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('web_pay');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('requestUrl', 'string', 250, array(
             'type' => 'string',
             'default' => 'https://3dsecure.exemple.com/order.do',
             'length' => 250,
             ));
        $this->hasColumn('merchantNumber', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('publicKey', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('privateKey', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('heslo', 'string', 7, array(
             'type' => 'string',
             'length' => 7,
             ));
        $this->hasColumn('lastOrderNum', 'integer', null, array(
             'type' => 'integer',
             'default' => 1,
             ));
        $this->hasColumn('mena_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('zeme_urceni_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('enabled', 'boolean', null, array(
             'type' => 'boolean',
             'default' => false,
             ));
        $this->hasColumn('img', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mena', array(
             'local' => 'mena_id',
             'foreign' => 'id'));

        $this->hasOne('ZemeUrceni', array(
             'local' => 'zeme_urceni_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}