<?php

/**
 * BaseMenaKurz
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $vychozi_mena
 * @property integer $cilova_mena
 * @property decimal $kurz
 * @property Mena $Vychozi
 * @property Mena $Cilova
 * 
 * @method integer  getVychoziMena()  Returns the current record's "vychozi_mena" value
 * @method integer  getCilovaMena()   Returns the current record's "cilova_mena" value
 * @method decimal  getKurz()         Returns the current record's "kurz" value
 * @method Mena     getVychozi()      Returns the current record's "Vychozi" value
 * @method Mena     getCilova()       Returns the current record's "Cilova" value
 * @method MenaKurz setVychoziMena()  Sets the current record's "vychozi_mena" value
 * @method MenaKurz setCilovaMena()   Sets the current record's "cilova_mena" value
 * @method MenaKurz setKurz()         Sets the current record's "kurz" value
 * @method MenaKurz setVychozi()      Sets the current record's "Vychozi" value
 * @method MenaKurz setCilova()       Sets the current record's "Cilova" value
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMenaKurz extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('mena_kurz');
        $this->hasColumn('vychozi_mena', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('cilova_mena', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('kurz', 'decimal', 18, array(
             'type' => 'decimal',
             'scale' => 9,
             'length' => 18,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mena as Vychozi', array(
             'local' => 'vychozi_mena',
             'foreign' => 'id'));

        $this->hasOne('Mena as Cilova', array(
             'local' => 'cilova_mena',
             'foreign' => 'id'));
    }
}