<?php

/**
 * BaseKosik
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $session_id
 * @property integer $zakaznik_id
 * @property integer $zbozi_id
 * @property integer $mena_id
 * @property float $mno
 * @property Zakaznik $Zakaznik
 * @property Zbozi $Zbozi
 * @property Mena $Mena
 * 
 * @method integer  getId()          Returns the current record's "id" value
 * @method string   getSessionId()   Returns the current record's "session_id" value
 * @method integer  getZakaznikId()  Returns the current record's "zakaznik_id" value
 * @method integer  getZboziId()     Returns the current record's "zbozi_id" value
 * @method integer  getMenaId()      Returns the current record's "mena_id" value
 * @method float    getMno()         Returns the current record's "mno" value
 * @method Zakaznik getZakaznik()    Returns the current record's "Zakaznik" value
 * @method Zbozi    getZbozi()       Returns the current record's "Zbozi" value
 * @method Mena     getMena()        Returns the current record's "Mena" value
 * @method Kosik    setId()          Sets the current record's "id" value
 * @method Kosik    setSessionId()   Sets the current record's "session_id" value
 * @method Kosik    setZakaznikId()  Sets the current record's "zakaznik_id" value
 * @method Kosik    setZboziId()     Sets the current record's "zbozi_id" value
 * @method Kosik    setMenaId()      Sets the current record's "mena_id" value
 * @method Kosik    setMno()         Sets the current record's "mno" value
 * @method Kosik    setZakaznik()    Sets the current record's "Zakaznik" value
 * @method Kosik    setZbozi()       Sets the current record's "Zbozi" value
 * @method Kosik    setMena()        Sets the current record's "Mena" value
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseKosik extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('kosik');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('session_id', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
        $this->hasColumn('zakaznik_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('zbozi_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mena_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('mno', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Zakaznik', array(
             'local' => 'zakaznik_id',
             'foreign' => 'id'));

        $this->hasOne('Zbozi', array(
             'local' => 'zbozi_id',
             'foreign' => 'zbozi_id'));

        $this->hasOne('Mena', array(
             'local' => 'mena_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}