<?php

/**
 * BasePobockyDoprava
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $pobocka_id
 * @property string $name
 * @property integer $mena_id
 * @property string $title
 * @property float $celkem
 * @property float $cena
 * @property clob $adresa
 * @property clob $provozni_doba
 * @property string $mapa_adresa
 * @property Mena $Mena
 * @property Doctrine_Collection $Doprava
 * @property Doctrine_Collection $Objednavky
 * @property Doctrine_Collection $Platby
 * 
 * @method integer             getPobockaId()     Returns the current record's "pobocka_id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method integer             getMenaId()        Returns the current record's "mena_id" value
 * @method string              getTitle()         Returns the current record's "title" value
 * @method float               getCelkem()        Returns the current record's "celkem" value
 * @method float               getCena()          Returns the current record's "cena" value
 * @method clob                getAdresa()        Returns the current record's "adresa" value
 * @method clob                getProvozniDoba()  Returns the current record's "provozni_doba" value
 * @method string              getMapaAdresa()    Returns the current record's "mapa_adresa" value
 * @method Mena                getMena()          Returns the current record's "Mena" value
 * @method Doctrine_Collection getDoprava()       Returns the current record's "Doprava" collection
 * @method Doctrine_Collection getObjednavky()    Returns the current record's "Objednavky" collection
 * @method Doctrine_Collection getPlatby()        Returns the current record's "Platby" collection
 * @method PobockyDoprava      setPobockaId()     Sets the current record's "pobocka_id" value
 * @method PobockyDoprava      setName()          Sets the current record's "name" value
 * @method PobockyDoprava      setMenaId()        Sets the current record's "mena_id" value
 * @method PobockyDoprava      setTitle()         Sets the current record's "title" value
 * @method PobockyDoprava      setCelkem()        Sets the current record's "celkem" value
 * @method PobockyDoprava      setCena()          Sets the current record's "cena" value
 * @method PobockyDoprava      setAdresa()        Sets the current record's "adresa" value
 * @method PobockyDoprava      setProvozniDoba()  Sets the current record's "provozni_doba" value
 * @method PobockyDoprava      setMapaAdresa()    Sets the current record's "mapa_adresa" value
 * @method PobockyDoprava      setMena()          Sets the current record's "Mena" value
 * @method PobockyDoprava      setDoprava()       Sets the current record's "Doprava" collection
 * @method PobockyDoprava      setObjednavky()    Sets the current record's "Objednavky" collection
 * @method PobockyDoprava      setPlatby()        Sets the current record's "Platby" collection
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePobockyDoprava extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('pobocky_doprava');
        $this->hasColumn('pobocka_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));
        $this->hasColumn('mena_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'length' => 50,
             ));
        $this->hasColumn('celkem', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('cena', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('adresa', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('provozni_doba', 'clob', null, array(
             'type' => 'clob',
             ));
        $this->hasColumn('mapa_adresa', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Mena', array(
             'local' => 'mena_id',
             'foreign' => 'id'));

        $this->hasMany('Doprava', array(
             'refClass' => 'DopravaPobocka',
             'local' => 'pobocka_id',
             'foreign' => 'doprava_id'));

        $this->hasMany('Objednavky', array(
             'local' => 'pobocka_id',
             'foreign' => 'pobocka_id'));

        $this->hasMany('Platby', array(
             'local' => 'pobocka_id',
             'foreign' => 'pobocka_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $sluggable0 = new Doctrine_Template_Sluggable(array(
             'unique' => true,
             'fields' => 
             array(
              0 => 'name',
             ),
             'canUpdate' => false,
             ));
        $this->actAs($timestampable0);
        $this->actAs($sluggable0);
    }
}