<?php

/**
 * AkceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AkceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AkceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Akce');
    }
}