<?php

/**
 * CenyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CenyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CenyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Ceny');
    }
}