<?php

/**
 * CisloObjTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CisloObjTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CisloObjTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CisloObj');
    }
}