<?php

/**
 * DodavatelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DodavatelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DodavatelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Dodavatel');
    }
}