<?php

/**
 * DopravaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DopravaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DopravaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Doprava');
    }
}