<?php

/**
 * DopravaPobockaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DopravaPobockaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DopravaPobockaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DopravaPobocka');
    }
}