<?php

/**
 * DPHTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DPHTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DPHTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DPH');
    }
}