<?php

/**
 * GalleryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GalleryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GalleryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gallery');
    }
    
    function retrieveForSelect($q, $limit = 5) {
        $q = Doctrine_Query::create()
                        ->from('Gallery')
                        ->andWhere('title like ?', '%' . $q . '%')
                        ->addOrderBy('title')
                        ->limit($limit);
        $items = array();
        foreach ($q->execute() as $item) {
            $items[$item->getId()] = (string) $item;
        }
        return $items;
    }
}