<?php

/**
 * KosikTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class KosikTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object KosikTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Kosik');
    }
}