<?php

/**
 * MenaKurzTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenaKurzTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MenaKurzTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MenaKurz');
    }
}