<?php

/**
 * MenaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MenaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MenaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Mena');
    }
}