<?php

/**
 * ObjednavkyPrijataTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjednavkyPrijataTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObjednavkyPrijataTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ObjednavkyPrijata');
    }
}