<?php

/**
 * ObjednavkyOdeslaneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjednavkyOdeslaneTable extends ObjednavkyPrijataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObjednavkyOdeslaneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ObjednavkyOdeslane');
    }
}