<?php

/**
 * ObjednavkyUkonceneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjednavkyUkonceneTable extends ObjednavkyPrijataTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObjednavkyUkonceneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ObjednavkyUkoncene');
    }
}