<?php

/**
 * ObjednavkyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObjednavkyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObjednavkyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Objednavky');
    }
}