<?php

/**
 * PayPalTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PayPalTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PayPalTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PayPal');
    }
}