<?php

/**
 * Platby
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    E Shop
 * @subpackage model
 * @author     Jan Damek, damekjan74@gmail.com
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Platby extends BasePlatby
{
}
