<?php

/**
 * PlatbyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlatbyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlatbyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Platby');
    }
}