<?php

/**
 * PobockyDopravaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PobockyDopravaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PobockyDopravaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PobockyDoprava');
    }
}