<?php

/**
 * PolozkyFakTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PolozkyFakTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PolozkyFakTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PolozkyFak');
    }
}