<?php

/**
 * SkupinaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SkupinaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SkupinaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Skupina');
    }
}