<?php

/**
 * SkupnaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SkupnaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SkupnaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Skupna');
    }
}