<?php

/**
 * SlozeniZboziTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlozeniZboziTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlozeniZboziTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SlozeniZbozi');
    }
}