<?php

/**
 * SlozeniTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SlozeniTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SlozeniTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Slozeni');
    }
}