<?php

/**
 * StavObjednavkyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class StavObjednavkyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object StavObjednavkyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('StavObjednavky');
    }
}