<?php

/**
 * WebPayTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WebPayTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WebPayTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WebPay');
    }
}