<?php

/**
 * ZaokrouhleniTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ZaokrouhleniTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ZaokrouhleniTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Zaokrouhleni');
    }
}