generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Gallery
    theme:                 jroller
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          gallery
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        display: [ is_active, title, description ]
        title: Galerie
        fields:
          is_active:
            label: Aktivní
          title:
            label: Titulek
          description:
            label: Popis
      filter:  ~
      form:
        display: [ title, description, keywords, path, image, ~showGalleryImages ]
        fields:
          is_active:
            label: Aktivní
          title:
            label: Titulek
      edit:
        title: Editace galerie
      new:
        title: Nová galerie


