# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            4a5sf4sa5dg4df5t45ert4gfd45

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    default_culture:        cs_CZ
    culture:                cs
    i18n:                   on
    
    enabled_modules:      [Partial, Cache, ImageResizer, CustomDate, Text, Date, Number, Navigation, I18N, sfGuardGroup, sfGuardUser, sfGuardPermission, sfGuardAuth, Url, Helper, sfPaymentPayPal ]
