# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    language:     cs
    robots:       index, follow

  stylesheets:    [style.css]

  javascripts:    
    - http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js
    - winsizer.js
    - colorbox/jquery.colorbox.js
    - jquery-ui-1.8.10.custom.min.js
    - scriptaculous-js-1.9.0/lib/prototype.js
    - scriptaculous-js-1.9.0/src/scriptaculous.js?load=effects,builder

  has_layout:     true
  layout:         layout
